version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:8200
    env_file: .env
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - db
  db:
    image: mongo
    env_file: .env
